### ISSUE TITLE
`encounter_counter` class instance method belongs to two different classes in `mythical-creatures/spec/ogre_spec.rb` on lines 28 and 82

### ISSUE THREAD

**Issue by brandenge** [turingschool-examples/ruby-exercises#133]
The `encounter_counter` class instance method belongs to both the `Ogre` and `Human` class, according to the tests

Line 28: `expect(human.encounter_counter).to eq(1)`

Line 82: `expect(ogre.encounter_counter).to eq(6)`

While I guess in theory it could belong to both classes, I don't think that makes much sense. Instead, I think the intent here is for it to belong to the `Human` class only, which would make more sense than having it belong to the `Ogre` class only.

If that is the case, then line 82 can be changed to: `expect(human.encounter_counter).to eq(6)`

**Comment by epintozzi** [comment]
I'm going to dig a little deeper into this one to make sure that isn't intentional.

**Comment by epintozzi** [comment]
Ah I see what you're saying now. Yep that makes sense. Good catch!
